[workspace]
resolver = "3"

members = [
    "genesis-contracts",
    "genesis-core",
    "genesis-cli",
    "genesis-replay",
    "genesis-plugins/plugin-dummy",
    "genesis-plugins/anchor-mmap",
    "genesis-plugins/brain-llm",
    "genesis-daemons/llm-dummy",
    "genesis-daemons/fantasy-dummy",
    "genesis-drivers/os-driver"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["玉帝哥哥 <yudi@genesis.net>"]
