#![allow(dead_code)]

// Project Lazarus code converter.
//
// This file converts a small, validated decision IR into Rust source code. It
// does not claim to translate arbitrary COBOL or Java. The safe boundary is:
// legacy source -> audited IR -> generated Rust -> rustc/CI verification.

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Expr {
    Input,
    ConstI64(i64),
    Add(Box<Expr>, Box<Expr>),
    Sub(Box<Expr>, Box<Expr>),
    Mul(Box<Expr>, Box<Expr>),
    Clamp {
        value: Box<Expr>,
        min: i64,
        max: i64,
    },
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Predicate {
    Always,
    Lt(i64),
    Le(i64),
    Eq(i64),
    Ge(i64),
    Gt(i64),
    And(Box<Predicate>, Box<Predicate>),
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DecisionArm {
    pub name: String,
    pub when: Predicate,
    pub value: Expr,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DecisionMatrix {
    pub module_name: String,
    pub function_name: String,
    pub arms: Vec<DecisionArm>,
    pub default: Expr,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ConversionReport {
    pub rust_source: String,
    pub warnings: Vec<String>,
}

pub fn compile_decision_matrix(matrix: &DecisionMatrix) -> Result<ConversionReport, String> {
    validate_identifier(&matrix.module_name, "module_name")?;
    validate_identifier(&matrix.function_name, "function_name")?;
    if matrix.arms.len() > 256 {
        return Err("decision matrix arm count exceeds 256".to_string());
    }

    let mut warnings = Vec::new();
    let mut source = String::new();
    source.push_str("// Generated by Project Lazarus CodeConverter.rs.\n");
    source.push_str("// Review and verify before production deployment.\n");
    source.push_str("#![allow(clippy::needless_return)]\n\n");
    source.push_str(&format!("pub mod {} {{\n", matrix.module_name));
    source.push_str(&format!(
        "    pub fn {}(input: i64) -> i64 {{\n",
        matrix.function_name
    ));

    let mut saw_always = false;
    for arm in &matrix.arms {
        validate_identifier(&arm.name, "arm.name")?;
        if saw_always {
            warnings.push(format!(
                "arm '{}' is unreachable after an Always predicate",
                arm.name
            ));
        }
        if arm.when == Predicate::Always {
            saw_always = true;
        }
        source.push_str(&format!("        // arm: {}\n", escape_comment(&arm.name)));
        source.push_str(&format!(
            "        if {} {{ return {}; }}\n",
            compile_predicate(&arm.when),
            compile_expr(&arm.value)
        ));
    }

    source.push_str(&format!(
        "        return {};\n",
        compile_expr(&matrix.default)
    ));
    source.push_str("    }\n");
    source.push_str("}\n");

    Ok(ConversionReport {
        rust_source: source,
        warnings,
    })
}

fn validate_identifier(value: &str, field: &str) -> Result<(), String> {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return Err(format!("{field} is required"));
    };
    if !(first == '_' || first.is_ascii_alphabetic()) {
        return Err(format!("{field} must start with '_' or an ASCII letter"));
    }
    if !chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric()) {
        return Err(format!(
            "{field} must contain only ASCII letters, digits, and '_'"
        ));
    }
    Ok(())
}

fn compile_predicate(predicate: &Predicate) -> String {
    match predicate {
        Predicate::Always => "true".to_string(),
        Predicate::Lt(value) => format!("input < {value}"),
        Predicate::Le(value) => format!("input <= {value}"),
        Predicate::Eq(value) => format!("input == {value}"),
        Predicate::Ge(value) => format!("input >= {value}"),
        Predicate::Gt(value) => format!("input > {value}"),
        Predicate::And(left, right) => {
            format!(
                "({}) && ({})",
                compile_predicate(left),
                compile_predicate(right)
            )
        }
    }
}

fn compile_expr(expr: &Expr) -> String {
    match expr {
        Expr::Input => "input".to_string(),
        Expr::ConstI64(value) => value.to_string(),
        Expr::Add(left, right) => {
            format!(
                "({}).saturating_add({})",
                compile_expr(left),
                compile_expr(right)
            )
        }
        Expr::Sub(left, right) => {
            format!(
                "({}).saturating_sub({})",
                compile_expr(left),
                compile_expr(right)
            )
        }
        Expr::Mul(left, right) => {
            format!(
                "({}).saturating_mul({})",
                compile_expr(left),
                compile_expr(right)
            )
        }
        Expr::Clamp { value, min, max } => {
            format!("({}).clamp({min}, {max})", compile_expr(value))
        }
    }
}

fn escape_comment(value: &str) -> String {
    value.replace('\n', " ").replace('\r', " ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn compiles_a_bounded_fee_matrix() {
        let matrix = DecisionMatrix {
            module_name: "fees".to_string(),
            function_name: "compute_fee".to_string(),
            arms: vec![
                DecisionArm {
                    name: "negative_is_zero".to_string(),
                    when: Predicate::Lt(0),
                    value: Expr::ConstI64(0),
                },
                DecisionArm {
                    name: "small_flat_fee".to_string(),
                    when: Predicate::Le(100),
                    value: Expr::ConstI64(1),
                },
            ],
            default: Expr::Clamp {
                value: Box::new(Expr::Mul(
                    Box::new(Expr::Input),
                    Box::new(Expr::ConstI64(2)),
                )),
                min: 2,
                max: 10_000,
            },
        };

        let report = compile_decision_matrix(&matrix).expect("matrix must compile");
        assert!(report.rust_source.contains("pub mod fees"));
        assert!(report
            .rust_source
            .contains("pub fn compute_fee(input: i64) -> i64"));
        assert!(report.rust_source.contains("saturating_mul"));
        assert!(report.warnings.is_empty());
    }

    #[test]
    fn rejects_invalid_identifiers() {
        let matrix = DecisionMatrix {
            module_name: "bad-name".to_string(),
            function_name: "compute".to_string(),
            arms: Vec::new(),
            default: Expr::Input,
        };
        assert!(compile_decision_matrix(&matrix).is_err());
    }
}
