use lazarus_contracts::{DecisionExpr, DecisionIr, LazarusJobEvent};
use lazarus_orchestrator::{LazarusOrchestrator, StateTransition};
use serde::{Deserialize, Serialize};
use sha2::{Digest as _, Sha256};
use std::fs;
use std::path::PathBuf;
use std::process::Command;

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ConversionArtifact {
    pub module_name: String,
    pub function_name: String,
    pub source: String,
    pub source_hash: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct CompileReceipt {
    pub artifact_path: PathBuf,
    pub output_path: PathBuf,
    pub artifact_hash: String,
}

#[derive(Clone, Debug)]
pub struct ConverterConfig {
    pub module_name: String,
    pub function_name: String,
    pub rustc_bin: PathBuf,
    pub out_dir: PathBuf,
}

impl ConverterConfig {
    pub fn new(
        module_name: impl Into<String>,
        function_name: impl Into<String>,
        out_dir: impl Into<PathBuf>,
    ) -> Self {
        Self {
            module_name: module_name.into(),
            function_name: function_name.into(),
            rustc_bin: PathBuf::from("rustc"),
            out_dir: out_dir.into(),
        }
    }
}

#[derive(Clone, Debug)]
pub struct ConversionOutput {
    pub artifact: ConversionArtifact,
    pub generated_transition: StateTransition,
}

#[derive(Clone, Debug)]
pub struct CompileOutput {
    pub receipt: CompileReceipt,
    pub compiled_transition: StateTransition,
}

pub fn convert_verified_ir(
    orchestrator: &mut LazarusOrchestrator,
    job_id: &str,
    ir: &DecisionIr,
    config: &ConverterConfig,
) -> Result<ConversionOutput, String> {
    ir.validate_bounded()?;
    validate_identifier(&config.module_name, "module_name")?;
    validate_identifier(&config.function_name, "function_name")?;
    let source = render_rust_source(ir, config)?;
    let source_hash = hex_sha256(source.as_bytes());
    let artifact = ConversionArtifact {
        module_name: config.module_name.clone(),
        function_name: config.function_name.clone(),
        source,
        source_hash: source_hash.clone(),
    };
    let generated_transition = orchestrator.apply(
        job_id,
        LazarusJobEvent::RustGenerated {
            artifact_hash: source_hash,
        },
    )?;
    Ok(ConversionOutput {
        artifact,
        generated_transition,
    })
}

pub fn compile_artifact(
    orchestrator: &mut LazarusOrchestrator,
    job_id: &str,
    artifact: &ConversionArtifact,
    config: &ConverterConfig,
) -> Result<CompileOutput, String> {
    fs::create_dir_all(&config.out_dir).map_err(|error| error.to_string())?;
    let artifact_path = config.out_dir.join(format!(
        "{}_{}.rs",
        artifact.module_name, artifact.function_name
    ));
    let output_path = config.out_dir.join(format!(
        "lib{}_{}.rlib",
        artifact.module_name, artifact.function_name
    ));
    fs::write(&artifact_path, &artifact.source).map_err(|error| error.to_string())?;

    let output = Command::new(&config.rustc_bin)
        .arg("--crate-type=lib")
        .arg("--edition=2024")
        .arg(&artifact_path)
        .arg("-o")
        .arg(&output_path)
        .output()
        .map_err(|error| format!("failed to spawn rustc: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "rustc failed with status {}: {}",
            output.status,
            String::from_utf8_lossy(&output.stderr)
        ));
    }

    let artifact_hash = hex_sha256(&fs::read(&artifact_path).map_err(|error| error.to_string())?);
    let receipt = CompileReceipt {
        artifact_path,
        output_path,
        artifact_hash: artifact_hash.clone(),
    };
    let compiled_transition =
        orchestrator.apply(job_id, LazarusJobEvent::CompilePassed { artifact_hash })?;
    Ok(CompileOutput {
        receipt,
        compiled_transition,
    })
}

fn render_rust_source(ir: &DecisionIr, config: &ConverterConfig) -> Result<String, String> {
    let mut params = ir
        .input_domains
        .keys()
        .filter(|name| name.as_str() != "__unit")
        .cloned()
        .collect::<Vec<_>>();
    params.sort();
    for param in &params {
        validate_identifier(param, "parameter")?;
    }
    let signature = params
        .iter()
        .map(|name| format!("{name}: i64"))
        .collect::<Vec<_>>()
        .join(", ");
    let expr = compile_expr(&ir.expression)?;

    Ok(format!(
        "// Generated by Project Lazarus lazarus-converter-pipeline.\n\
// Source IR: {}\n\
pub mod {} {{\n\
    pub fn {}({}) -> i64 {{\n\
        {}\n\
    }}\n\
}}\n",
        escape_comment(&ir.ir_id),
        config.module_name,
        config.function_name,
        signature,
        expr
    ))
}

fn compile_expr(expr: &DecisionExpr) -> Result<String, String> {
    match expr {
        DecisionExpr::Const { value } => Ok(value.to_string()),
        DecisionExpr::Var { name } => {
            validate_identifier(name, "var")?;
            Ok(name.clone())
        }
        DecisionExpr::Add { left, right } => Ok(format!(
            "({}).saturating_add({})",
            compile_expr(left)?,
            compile_expr(right)?
        )),
        DecisionExpr::Sub { left, right } => Ok(format!(
            "({}).saturating_sub({})",
            compile_expr(left)?,
            compile_expr(right)?
        )),
        DecisionExpr::Mul { left, right } => Ok(format!(
            "({}).saturating_mul({})",
            compile_expr(left)?,
            compile_expr(right)?
        )),
        DecisionExpr::Min { left, right } => Ok(format!(
            "std::cmp::min({}, {})",
            compile_expr(left)?,
            compile_expr(right)?
        )),
        DecisionExpr::Max { left, right } => Ok(format!(
            "std::cmp::max({}, {})",
            compile_expr(left)?,
            compile_expr(right)?
        )),
        DecisionExpr::Abs { value } => Ok(format!("({}).saturating_abs()", compile_expr(value)?)),
    }
}

fn validate_identifier(value: &str, field: &str) -> Result<(), String> {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return Err(format!("{field} is required"));
    };
    if !(first == '_' || first.is_ascii_alphabetic()) {
        return Err(format!("{field} must start with '_' or ASCII letter"));
    }
    if !chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric()) {
        return Err(format!(
            "{field} must contain only ASCII letters, digits, and '_'"
        ));
    }
    Ok(())
}

fn hex_sha256(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    format!("{:x}", hasher.finalize())
}

fn escape_comment(value: &str) -> String {
    value.replace(['\n', '\r'], " ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use lazarus_contracts::{DecisionExpr, LazarusJobState};
    use lazarus_orchestrator::LazarusOrchestrator;
    use std::collections::BTreeMap;

    #[test]
    fn converts_ir_and_advances_to_generated() {
        let mut orchestrator = orchestrator_at_verified();
        let config = test_config("generated");
        let output =
            convert_verified_ir(&mut orchestrator, "job-1", &sample_ir(), &config).unwrap();

        assert!(
            output
                .artifact
                .source
                .contains("pub fn compute_fee(input: i64) -> i64")
        );
        assert_eq!(output.generated_transition.to, LazarusJobState::Generated);
        assert_eq!(
            orchestrator.job("job-1").unwrap().state,
            LazarusJobState::Generated
        );
    }

    #[test]
    fn compiles_artifact_and_advances_to_compiled() {
        let mut orchestrator = orchestrator_at_verified();
        let config = test_config("compiled");
        let conversion =
            convert_verified_ir(&mut orchestrator, "job-1", &sample_ir(), &config).unwrap();
        let compile =
            compile_artifact(&mut orchestrator, "job-1", &conversion.artifact, &config).unwrap();

        assert!(compile.receipt.artifact_path.is_file());
        assert!(compile.receipt.output_path.is_file());
        assert_eq!(compile.compiled_transition.to, LazarusJobState::Compiled);
        assert_eq!(
            orchestrator.job("job-1").unwrap().state,
            LazarusJobState::Compiled
        );
    }

    #[test]
    fn rejects_invalid_module_identifier() {
        let mut orchestrator = orchestrator_at_verified();
        let mut config = test_config("bad_id");
        config.module_name = "bad-name".to_string();

        assert!(convert_verified_ir(&mut orchestrator, "job-1", &sample_ir(), &config).is_err());
    }

    fn orchestrator_at_verified() -> LazarusOrchestrator {
        let mut orchestrator = LazarusOrchestrator::new();
        orchestrator.create_job("job-1", "bank-core").unwrap();
        orchestrator
            .apply(
                "job-1",
                LazarusJobEvent::ScanCompleted {
                    graph_hash: "0123456789abcdef".to_string(),
                },
            )
            .unwrap();
        orchestrator
            .apply(
                "job-1",
                LazarusJobEvent::IrExtracted {
                    ir_hash: "0123456789abcdef".to_string(),
                },
            )
            .unwrap();
        orchestrator
            .apply(
                "job-1",
                LazarusJobEvent::BoundedVerificationPassed {
                    report_hash: "0123456789abcdef".to_string(),
                },
            )
            .unwrap();
        orchestrator
    }

    fn sample_ir() -> DecisionIr {
        DecisionIr {
            ir_id: "sample-ir".to_string(),
            source_unit_id: "bank/src/lib.rs".to_string(),
            input_domains: BTreeMap::from([("input".to_string(), vec![-1, 0, 1])]),
            expression: DecisionExpr::Mul {
                left: Box::new(DecisionExpr::Var {
                    name: "input".to_string(),
                }),
                right: Box::new(DecisionExpr::Const { value: 2 }),
            },
            side_effects: Vec::new(),
            invariants: Vec::new(),
        }
    }

    fn test_config(name: &str) -> ConverterConfig {
        ConverterConfig::new(
            "fees",
            "compute_fee",
            std::env::temp_dir().join(format!(
                "lazarus-converter-pipeline-{name}-{}",
                std::process::id()
            )),
        )
    }
}
